<a href="https://colab.research.google.com/github/carlosenciso/MACHINE_LEARNING/blob/master/Naive_Bayes_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><center><strong>Machine Learning 04. Bayes Naives</strong></center></h1>

# 1. Installing a library that is not in Colaboratory

To import a library that's not in Colaboratory by default, you can use `!pip install` or `!apt-get install`.

In [ ]:
!pip install geopandas
!pip install xarray 
!pip install rioxarray
!pip install cmocean
!pip install seaborn

# 2. Mount Drive
Mount remotely your google drive to get access into Dataset

In [ ]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import os
import cmocean as cmo
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# 3. Reading Dataset Titanic surviver
Preprocess open dataset from titanic statistics

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv')

In [21]:
df.groupby('Category').describe()

Message                                                               
           count unique                                                top freq
Category                                                                       
ham         4825   4516                             Sorry, I'll call later   30
spam         747    641  Please call our customer service representativ...    4

## 3.1. Convert categorical data into numerical type

In [22]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

## 3.2. Split dataset intro train and test data

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.25)

## 3.3. Extration test

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# 4. Import model

## 4.1. Call Multinomial model

In [29]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

## 4.2. Check out some outputs

In [33]:
emails = [
          'Hey mohan, can we get together to watch football game tomorrow',
          'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward'
]
emails_count = v.transform(emails) 
model.predict(emails_count)

array([0, 1])

## 4.3. Verifying score model

In [34]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9827709978463748

# 5. Using Pipeline

In [35]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
                ('vectorizer', CountVectorizer()),
                ('nb', MultinomialNB())
])

In [36]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [37]:
clf.score(X_test, y_test)

0.9827709978463748

In [38]:
clf.predict(emails)

array([0, 1])